---
title: "Academic and career experience"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: sandstone
---

## Resume

<font size="6"><b>KE XU</b></font>

<font size="5"><b>Education</b></font>

<font size="4"><b>Columbia University</b></font>

<font size="3">M.S. in Biostatistics</font>

<font size="3">New York, USA</font>

<font size="3">Sep. 2021 - Jun. 2023</font>


<font size="4"><b>Xi'an Jiaotong-Liverpool University</b></font>

<font size="3">B.S. in Financial Mathematics</font>

<font size="3">Suzhou, China</font>

<font size="3">Feb. 2016 - Jun. 2020</font>



<font size="5"><b>Relevant Experience</b></font>

<font size="4"><b>Etoro Ltd</b></font>

<font size="3">Jan. 2018 - Feb. 2018</font>

<font size="3"><i>Quantitative Analytics Assistant, Winter Intern</i></font>

<font size="3">Shanghai, China</font>

<font size="3"><li>Study and assist in FX trading programs, do mock trading on the platform and predict the trend of foreign exchange, then make the risk management;</li></font>

<font size="3"><li>Collect the stock data from hundreds of companies, make the analysis report in fundamental as well as technical aspects, and predict stock trend;</li></font>

<font size="3"><li>Write daily reports of exchange rate, analyze the market and give the presentation.</li></font>

<font size="4"><b>The Bank of Communication</b></font>

<font size="3">Aug. 2018</font>

<font size="3"><i>International department, Intern</i></font>

<font size="3">Shenzhen, China</font>

<font size="3"><li>Supervise Foreign exchange, and check error reports of cross-border business of Chinese yuan as well as money orders from branch banks;</li></font>

<font size="3"><li>Maintain internal system, update the newly data of money market behavior and report potential errors immediately to head office;</li></font>

<font size="3"><li>Collect updated news from National Foreign Exchange Administration and make it into training booklet, help prepare materials of a 500 people training meeting (like slides, paper material and all materials relevant to office software) for the foreign exchange policy.</li></font>

<font size="5"><b>Extracurricular activities</b></font>

<font size="4"><b>Stock portfolio analysis based on Artificial Intelligent trading</b></font>

<font size="3">Jun. 2019 - Dec. 2019</font>

<font size="3"><i>Research assistant</i></font>

<font size="3">Suzhou, China</font>

<font size="3"><li>Learn and collate fundamental functions in Python and deliver training courses to team members; </li></font>

<font size="3"><li>Provide Python support at the early stage of the project;</li></font>

<font size="3"><li>Make and maintain intercommunicating web pages, explain the project and update newly data of stock portfolio on web-pages.</li></font>

<font size="4"><b>Modelling competition for national graduates</b></font>

<font size="3">Dec. 2018 - Jan. 2019</font>

<font size="3"><i>Team leader</i></font>

<font size="3">Suzhou, China</font>

<font size="3"><li>Participate the modelling competition host in America and be the leader of the team;</li></font>

<font size="3"><li>Make time management during the limited time and prepare for learning material for competition topics;</li></font>

<font size="3"><li>Collect, filter and analyze relevant data and write the final report.</li></font>

<font size="5"><b>Skills</b></font>

<font size="3">Excel VBA</font>

<font size="3">Python</font>

<font size="3">STATA</font>

<font size="3">SPSS</font>

<font size="3">MATLAB</font>

<font size="3">Java</font>



## Back
<font size="4">Back to [home page](index.html)</font>